#!/usr/bin/bash 

# set -x  # Enable command tracing (debugging)


echo "Enter Pokemeon ID or Name "

read pokemon_id


API_URL="https://pokeapi.co/api/v2/pokemon/$pokemon_id"


OUTPUT_FILE="data.json"

http_response=$(curl -s "$API_URL" -w "%{http_code}" -o "$OUTPUT_FILE" )

if [ $? -ne 0 ]; then
    echo "Curl failed to execute. Exit code: $?." >> "errors.txt"
    
# Check if curl succeeded (exit status 0)
elif [ "$http_response" -eq 200 ]; then
    echo "Pokemon data saved to $OUTPUT_FILE."
else
    # Write the error code to the errors file
    echo "Error: Failed to fetch data for $pokemon_id. HTTP Status Code: $http_response" >> "errors.txt"
fi



