#!/usr/bin/bash 


# Command to read data.json file 
# data=jq '{name, height, weight, type:.types[0].type.name}' data.json

name=$(jq -r '.name' data.json)
type=$(jq -r '.types[0].type.name' data.json)
weight=$(jq -r '.weight' data.json)
height=$(jq -r '.height' data.json)


# Convert weight from grams to kilograms using awk
formatted_weight=$(echo "$weight" | awk '{print $1/1000}')

# Convert height from centimeters to meters using awk
formatted_height=$(echo "$height" | awk '{print $1/100}')

# Format the output in a human-readable way using sed (example of pattern replaceme
echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall." | sed 's/\.0*//' | awk '{print $0}'

